# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0a54f3110dc2225ce380a1d53e3a856558e68da468fc29c6f867c5d1ed2ece82015b702f2daea59ee374cab717d56b35999c96b9daecd39fc64cbf39d9bc03a

test:
  secret_key_base: c81413c78dbea7c2273fd4223ba0f4e1788622893ccc0ac3686c44cfcf58cbb4a174153a8a92951e08a56b20219ddacaf1ee755168d0d187cd86cb606654fd39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
